name: Deploy To Production

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]
    
jobs:
  Deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Sync files with rsync
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -av
          path: .
          remote_path: /home/${{ secrets.SSH_USER }}/api/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install python requirements
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          scripts: |
            cd /home/${{ secrets.SSH_USER }}/api
            source venv/bin/active
            pip install -r requirements.txt
            deactivate

      - name: Restart API service
        id: req
        uses: fjogeleit/http-request-action@master
        with:
          url: https://api.taptwice.dev/services/self/restart?key=${{secrets.API_KEY_SERVICES}}
          method: "GET"
      - name: Show Response
        run: echo ${{ steps.req.outputs.response }}
        
        #run: rsync -av ~/work/GoogleDiscordBot/GoogleDiscordBot/GoogleBot/bin/Release/net6.0/debian.10-x64/publish/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/googlediscordbot/publish
